otus<-read.table("human_pathway.tsv",sep = "\t",header = T,row.names = 1)
map<-read.table("mappingfile_all.txt",sep = "\t",header=T,row.names=1)
tax<-read.table(file= "annotation_fish.tsv",header = T,row.names = 1,sep = "\t",quote = "")
otus_m<-as.matrix(otus)
tax_m<-as.matrix(tax)
otus_p = otu_table(otus_m, taxa_are_rows = TRUE)
tax_p = tax_table(tax_m)
map_p<-sample_data(map)
unfiltered <- merge_phyloseq(otus_p, map_p, tax_p)
save(unfiltered,file= "pathway_physeq_raw.data")
core_VSL<-unfiltered
otu_table(core_VSL) <- otu_table(core_VSL) + 1
myfunction <- function(core_VSL, Type,core_VSL_out,core_VSL_filter_out){
type<-as.formula(paste("~",Type,sep = ""))
type_group = get_variable(core_VSL, Type)
core_VS_ds = phyloseq_to_deseq2(core_VSL, type)
core_VS_ds<-estimateSizeFactors(core_VS_ds)
core_VS_ds<-estimateDispersions(core_VS_ds, fitType="local")
core_VS_ds<-varianceStabilizingTransformation(core_VS_ds, fitType="local")
counts_core_VSL_tt <- as.matrix(assay(core_VS_ds)) # assay() access transformed data matrix from DESeq2 objct
core_VSL_tt<-core_VSL
otu_table(core_VSL_tt) <- otu_table(counts_core_VSL_tt, taxa_are_rows = TRUE)
type_group = get_variable(core_VSL, "sub_Treat")
core_VS_ds = phyloseq_to_deseq2(core_VSL, type)
dds_mtx = DESeq(core_VS_ds, fitType = "local", test = "Wald", betaPrior = FALSE)
res_mtx = results(dds_mtx, cooksCutoff = FALSE)
pwy_rank = names(sort(taxa_sums(core_VSL_tt), decreasing=TRUE))
pwy_rkmx<-cbind(pwy_rank,c(1:length(pwy_rank)))
colnames(pwy_rkmx)<-c("pathway","rank")
pwy_rank_phy = prune_taxa(pwy_rank, core_VSL_tt)
taxon<-tax_table(core_VSL_tt)
taxon<-as.data.frame(taxon)
taxon$pwy_name<-row.names(taxon)
taxon_rank<-merge(taxon,pwy_rkmx,by.x="pwy_name",by.y="pathway",all.x=T)
res_mtx_df <- data.frame(res_mtx)
res_mtx_df$pathway<-row.names(res_mtx_df)
res_mtx_ant <- merge(res_mtx_df,taxon_rank,by.x="pathway",by.y="pwy_name")
write.table(res_mtx_ant,file=core_VSL_out,sep="\t",row.names = F,quote = F)
alpha=0.05
sigtab_mtx = res_mtx_ant[which(res_mtx_ant$padj < alpha), ]
write.table(sigtab_mtx,file=core_VSL_filter_out,sep="\t",row.names = F,quote = F)
}
hu0_hu7<-subset_samples(core_VSL, Treat == "Human")
myfunction(hu0_hu7,"sub_Treat","hu0_hu7_log2FC.txt","hu0_hu7_log2FC_filtered")
pathway = read.table("hu0_hu7_log2FC_filtered.txt",header=T,sep="\t")
pp = ggplot(pathway,aes(log2FoldChange,Pathway))
pp + geom_point()
pp + geom_point(aes(size=Abundance))
pbubble = pp + geom_point(aes(size=Abundance,color=Qvalue))
pbubble + scale_colour_gradient(low="darkseagreen1",high="deepskyblue2")
